### ISSUE TITLE
Could you release the MKG-W and MKG-Y dataset?

### ISSUE THREAD

**Issue by Zhang-Each** [quqxui/MMRNS#1]
I found that only MMKB-DB15K dataset is released in the dropbox link. Could you release the MKG-W and MKG-Y dataset mentioned in the paper?

**Comment by quqxui** [comment]
Thanks very for your attention to our paper. We have uploaded the raw data and embeddings of MKG-W and MKG-Y datasets, with three images for each entity. You can download them from https://www.aliyundrive.com/s/piMyCgT9G76 . The link in the README.MD is also changed.

**Comment by Zhang-Each** [comment]
> Thanks very for your attention to our paper. We have uploaded the raw data and embeddings of MKG-W and MKG-Y datasets, with three images for each entity. You can download them from https://www.aliyundrive.com/s/piMyCgT9G76 . The link in the README.MD is also changed.

Thanks a lot!

**Comment by quqxui** [comment]
Sorry, It seems that Aliyundrive do not allow to share the file with type of .zip or .h5. So I have uploaded the datasets to Baidu drive, you can download them from 

url: https://pan.baidu.com/s/1gDwaGD0r8AJhYAXGxOc9Cg 

code: 758p

**Comment by Zhang-Each** [comment]
> Sorry, It seems that Aliyundrive do not allow to share the file with type of .zip or .h5. So I have uploaded the datasets to Baidu drive, you can download them from
> 
> url: https://pan.baidu.com/s/1gDwaGD0r8AJhYAXGxOc9Cg
> 
> code: 758p

Thank you!

**Comment by wyZhang016** [comment]
Hello, it seems that the Baidu drive you sent has expired. Could you please send it again?

**Comment by quqxui** [comment]
We reload files to Baidu drive, and you can download from :

url: https://pan.baidu.com/s/10FR91rwqO-2AyK4S9aP--g?pwd=zu68

code : zu68

I am not sure when it will be expired, so download them as soon as possible.

**Comment by wyZhang016** [comment]
> zu68

Sorry, I just saw the reply today, could you please send it again? I will download it as soon as possible this time, thank you very much.

**Comment by quqxui** [comment]
url: https://pan.baidu.com/s/14jbRBUn25i7oDEqgH9DowQ?pwd=87ne#list/path=%2F

code : 87ne

There are the embeddings data and triples. I found the raw data cannot be shared in baidu drive, due to  "此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！"

So you can use the embeddings or you can download raw data from google drive: 

https://drive.google.com/drive/folders/1sFC-P9RKnikqNXjmLcj0IX7x5zvRs-Yj

**Comment by wyZhang016** [comment]
Thank you very much.

**Comment by kkcode111** [comment]
Hello! I wonder how to get the images of the MMKB-DB15K dataset. I see that the URL only provides .txt files. Thank you!

**Comment by quqxui** [comment]
The images in the MMKB-DB15K dataset originate from https://github.com/mniepert/mmkb, which provides the [download-images.py](https://github.com/mniepert/mmkb/blob/master/download-images.py) script for downloading images using the URLs in .txt files.

**Comment by kkcode111** [comment]
> MMKB-DB15K数据集中的图像来源于 https://github.com/mniepert/mmkb，提供了利用.txt文件中URL下载图像的 [download-images.py 脚本](https://github.com/mniepert/mmkb/blob/master/download-images.py)。

So, to download the images, I have to use the [download-images.py] to do it myself and you don’t have any pre-downloaded image archive files like MKG-W.zip available here right?thanks！

**Comment by quqxui** [comment]
> > MMKB-DB15K数据集中的图像来源于 [https://github.com/mniepert/mmkb，提供了利用.txt文件中URL下载图像的](https://github.com/mniepert/mmkb%EF%BC%8C%E6%8F%90%E4%BE%9B%E4%BA%86%E5%88%A9%E7%94%A8.txt%E6%96%87%E4%BB%B6%E4%B8%ADURL%E4%B8%8B%E8%BD%BD%E5%9B%BE%E5%83%8F%E7%9A%84) [download-images.py 脚本](https://github.com/mniepert/mmkb/blob/master/download-images.py)。
> 
> So, to download the images, I have to use the [download-images.py] to do it myself and you don’t have any pre-downloaded image archive files like MKG-W.zip available here right?thanks！

Yes, we do not retain the raw images. You can download them by yourself.
Best regards.
